#!/bin/sh

TMP_FILE=/tmp/dump.sql.gz

aws s3 cp s3://$S3_BUCKET/$BASE_PATH.sql.gz $TMP_FILE && \
  gunzip -c $TMP_FILE | mysql --protocol tcp -u $MYSQL_USER -h $MYSQL_HOST -p$MYSQL_PASSWORD && \
  rm $TMP_FILE
